using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using triaxis.WebForms.SourceGenerator.Model;

namespace triaxis.WebForms.SourceGenerator.Emit
{
    /// <summary>
    /// Emits an <c>ASP.ApplicationBrowserCapabilitiesFactory : BrowserCapabilitiesFactory</c>
    /// from the merged set of <c>App_Browsers\*.browser</c> entries. At
    /// request time the runtime walks the inherited <c>BrowserCapabilitiesFactory</c>
    /// tree, then drops into our <c>&lt;Parent&gt;ProcessBrowsers</c> overrides
    /// for any built-in parent any app-defined entry hangs off of.
    /// Mirrors the shape <c>aspnet_compiler</c> emits so its ILSpy
    /// decompilation lines up with ours.
    /// </summary>
    internal static class BrowserCapabilitiesFactoryEmitter
    {
        private const int ClassIndent = 1;
        private const int MemberIndent = 2;

        public static string Emit(ImmutableArray<BrowserEntry> entries, Compilation compilation)
        {
            // Group app-defined entries by their parent. Refining entries
            // (refID set) are attached to the parent named by refID; new
            // entries (id + parentID) are attached to parentID.
            var byParent = new Dictionary<string, List<BrowserEntry>>(StringComparer.OrdinalIgnoreCase);
            foreach (BrowserEntry entry in entries)
            {
                string? parent = entry.RefId ?? entry.ParentId;
                if (parent is null) continue;
                if (!byParent.TryGetValue(parent, out List<BrowserEntry>? list))
                {
                    list = new List<BrowserEntry>();
                    byParent[parent] = list;
                }
                list.Add(entry);
            }

            // Method name per entry. Refining entries get "<Parent>refbrowserid<A|B|…>"
            // (one letter per refining sibling, in declaration order — matches
            // aspnet_compiler's per-parent counter). New entries are PascalCased
            // from their id ("IE11" → "Ie11").
            var methodName = new Dictionary<BrowserEntry, string>();
            foreach (KeyValuePair<string, List<BrowserEntry>> kvp in byParent)
            {
                int refIndex = 0;
                foreach (BrowserEntry entry in kvp.Value)
                {
                    if (entry.RefId != null)
                    {
                        methodName[entry] = PascalCase(kvp.Key) + "refbrowserid" + (char)('A' + refIndex) + "Process";
                        refIndex++;
                    }
                    else if (entry.Id != null)
                    {
                        methodName[entry] = PascalCase(entry.Id) + "Process";
                    }
                }
            }

            // Depth in the application tree. Built-in parents are at depth 1
            // (the root of the runtime's tree as far as the app is concerned),
            // so first-level app-defined entries land at depth 2, and so on.
            // Refining entries don't add a node, so they don't get a depth.
            var depth = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            foreach (BrowserEntry entry in entries)
            {
                if (entry.Id != null && entry.RefId is null)
                {
                    depth[entry.Id] = DepthOf(entry.ParentId, depth);
                }
            }

            // Did anything use the User-Agent for identification? If so the
            // PopulateMatchedHeaders override registers the empty header key
            // so the runtime hands the User-Agent string in via the match
            // dictionary at request time.
            bool referencesUserAgent = entries.Any(e =>
                e.IdentificationUserAgentMatches.Length > 0
                || e.IdentificationUserAgentNonMatches.Length > 0
                || e.CaptureUserAgentPatterns.Length > 0);

            // Only emit `<Parent>ProcessBrowsers` overrides for parents that
            // are BUILT-IN — the runtime's tree already has those, so the
            // override is how we hook in. App-defined parents (entries with
            // an id of their own) recurse into their children from inside
            // their own Process method, no override needed.
            var appDefinedIds = entries
                .Where(e => e.Id != null && e.RefId is null)
                .Select(e => e.Id!)
                .ToImmutableHashSet(StringComparer.OrdinalIgnoreCase);

            IndentedTextWriter w = CodeWriter.Create(0);
            w.Line("// <auto-generated/>");
            w.Line("#nullable disable");
            using (w.Block("namespace ASP"))
            using (w.Block("public class ApplicationBrowserCapabilitiesFactory : global::System.Web.Configuration.BrowserCapabilitiesFactory"))
            {
                EmitConfigureCustomCapabilities(w);
                w.Blank();
                foreach (string parent in byParent.Keys.OrderBy(p => p, StringComparer.Ordinal))
                {
                    if (appDefinedIds.Contains(parent))
                    {
                        continue;
                    }
                    EmitParentProcessBrowsers(w, parent, byParent[parent], methodName);
                    w.Blank();
                }
                foreach (BrowserEntry entry in entries)
                {
                    if (methodName.TryGetValue(entry, out string? name))
                    {
                        EmitEntryProcess(w, entry, name, byParent, methodName, compilation);
                        w.Blank();
                    }
                }
                EmitPopulateMatchedHeaders(w, referencesUserAgent);
                w.Blank();
                EmitPopulateBrowserElements(w, entries, depth);
            }

            return w.ToSource();
        }

        private static int DepthOf(string? parentId, Dictionary<string, int> depth)
        {
            if (parentId != null && depth.TryGetValue(parentId, out int d))
            {
                return d + 1;
            }
            // Parent is a built-in browser (Default, Mozilla, IE, …). aspnet_compiler
            // treats those as depth-1 anchors so the first app-defined level lands
            // at depth 2.
            return 2;
        }

        private static void EmitConfigureCustomCapabilities(IndentedTextWriter w)
        {
            using (w.Block("public override void ConfigureCustomCapabilities(global::System.Collections.Specialized.NameValueCollection headers, global::System.Web.HttpBrowserCapabilities browserCaps)"))
            {
            }
        }

        private static void EmitParentProcessBrowsers(
            IndentedTextWriter w,
            string parent,
            List<BrowserEntry> children,
            Dictionary<BrowserEntry, string> methodName)
        {
            string parentMethod = PascalCase(parent);
            using (w.Block($"protected override void {parentMethod}ProcessBrowsers(bool ignoreApplicationBrowsers, global::System.Collections.Specialized.NameValueCollection headers, global::System.Web.HttpBrowserCapabilities browserCaps)"))
            {
                // Refining entries (refID set) run unconditionally — they
                // augment an already-matched parent. New entries are gated
                // on `!ignoreApplicationBrowsers` and short-circuit through
                // a nested-if chain so a successful match halts further
                // sibling probes.
                int openedIfs = 0;
                foreach (BrowserEntry child in children)
                {
                    if (child.RefId != null)
                    {
                        w.Line($"{methodName[child]}(headers, browserCaps);");
                    }
                }
                foreach (BrowserEntry child in children)
                {
                    if (child.RefId is null && child.Id != null)
                    {
                        string condition = openedIfs == 0
                            ? $"!ignoreApplicationBrowsers && !{methodName[child]}(headers, browserCaps)"
                            : $"!{methodName[child]}(headers, browserCaps)";
                        w.Line($"if ({condition})");
                        w.Line("{");
                        w.Indent++;
                        openedIfs++;
                    }
                }
                for (int i = 0; i < openedIfs; i++)
                {
                    w.Indent--;
                    w.Line("}");
                }
            }
        }

        private static void EmitEntryProcess(
            IndentedTextWriter w,
            BrowserEntry entry,
            string methodName,
            Dictionary<string, List<BrowserEntry>> byParent,
            Dictionary<BrowserEntry, string> entryMethodName,
            Compilation compilation)
        {
            using (w.Block($"private bool {methodName}(global::System.Collections.Specialized.NameValueCollection headers, global::System.Web.HttpBrowserCapabilities browserCaps)"))
            {
                w.Line("global::System.Collections.IDictionary capabilities = browserCaps.Capabilities;");

                bool needsText = entry.IdentificationUserAgentMatches.Length > 0
                    || entry.IdentificationUserAgentNonMatches.Length > 0
                    || entry.IdentificationCapabilityMatches.Length > 0;
                bool needsRegexWorker = needsText || entry.CaptureUserAgentPatterns.Length > 0
                    || entry.Capabilities.Any(c => c.Value.Contains("${"));

                if (needsText)
                {
                    string firstSource = FirstIdentificationSource(entry);
                    w.Line($"string text = {firstSource};");
                }
                if (needsRegexWorker)
                {
                    w.Line("global::System.Web.Configuration.RegexWorker val = new global::System.Web.Configuration.RegexWorker(browserCaps);");
                }

                EmitIdentificationProbes(w, entry);
                EmitCaptureProbes(w, entry);
                EmitCapabilitySetters(w, entry);
                EmitControlAdapters(w, entry, compilation);

                if (entry.Id != null && entry.RefId is null)
                {
                    w.Line($"browserCaps.AddBrowser(\"{entry.Id}\");");
                }

                // Recurse into children: same nested-if chain as the parent
                // ProcessBrowsers override, but without the
                // !ignoreApplicationBrowsers gate (children inherit the
                // parent's gate, and they're always app-defined here).
                if (entry.Id != null && byParent.TryGetValue(entry.Id, out List<BrowserEntry>? children))
                {
                    int openedIfs = 0;
                    foreach (BrowserEntry child in children)
                    {
                        if (child.RefId != null)
                        {
                            w.Line($"{entryMethodName[child]}(headers, browserCaps);");
                        }
                    }
                    foreach (BrowserEntry child in children)
                    {
                        if (child.RefId is null && child.Id != null)
                        {
                            w.Line($"if (!{entryMethodName[child]}(headers, browserCaps))");
                            w.Line("{");
                            w.Indent++;
                            openedIfs++;
                        }
                    }
                    for (int i = 0; i < openedIfs; i++)
                    {
                        w.Indent--;
                        w.Line("}");
                    }
                }

                w.Line("return true;");
            }
        }

        private static string FirstIdentificationSource(BrowserEntry entry)
        {
            // aspnet_compiler initialises `text` with the FIRST identification
            // source, then reassigns it before each subsequent probe — so the
            // initialiser matches whatever probe runs first.
            if (entry.IdentificationUserAgentMatches.Length > 0
                || entry.IdentificationUserAgentNonMatches.Length > 0
                || entry.IdentificationCapabilityMatches.Length == 0)
            {
                return "browserCaps[string.Empty]";
            }
            string firstCap = entry.IdentificationCapabilityMatches[0].Capability;
            return $"(string)capabilities[{CodeLiteral.Escape(firstCap)}]";
        }

        private static void EmitIdentificationProbes(IndentedTextWriter w, BrowserEntry entry)
        {
            bool first = true;
            foreach (string match in entry.IdentificationUserAgentMatches)
            {
                if (!first)
                {
                    w.Line("text = browserCaps[string.Empty];");
                }
                w.Line($"if (!val.ProcessRegex(text, {CodeLiteral.Escape(match)}))");
                w.Line("{");
                w.Indent++;
                w.Line("return false;");
                w.Indent--;
                w.Line("}");
                first = false;
            }
            foreach (string nonMatch in entry.IdentificationUserAgentNonMatches)
            {
                if (!first)
                {
                    w.Line("text = browserCaps[string.Empty];");
                }
                w.Line($"if (val.ProcessRegex(text, {CodeLiteral.Escape(nonMatch)}))");
                w.Line("{");
                w.Indent++;
                w.Line("return false;");
                w.Indent--;
                w.Line("}");
                first = false;
            }
            foreach ((string cap, string pattern) in entry.IdentificationCapabilityMatches)
            {
                if (!first)
                {
                    w.Line($"text = (string)capabilities[{CodeLiteral.Escape(cap)}];");
                }
                w.Line($"if (!val.ProcessRegex(text, {CodeLiteral.Escape(pattern)}))");
                w.Line("{");
                w.Indent++;
                w.Line("return false;");
                w.Indent--;
                w.Line("}");
                first = false;
            }
        }

        private static void EmitCaptureProbes(IndentedTextWriter w, BrowserEntry entry)
        {
            foreach (string pattern in entry.CaptureUserAgentPatterns)
            {
                w.Line($"val.ProcessRegex(browserCaps[string.Empty], {CodeLiteral.Escape(pattern)});");
            }
        }

        private static void EmitCapabilitySetters(IndentedTextWriter w, BrowserEntry entry)
        {
            foreach ((string name, string value) in entry.Capabilities)
            {
                string rhs = value.Contains("${")
                    ? $"val[{CodeLiteral.Escape(value)}]"
                    : CodeLiteral.Escape(value);
                w.Line($"capabilities[{CodeLiteral.Escape(name)}] = {rhs};");
            }
        }

        private static void EmitControlAdapters(IndentedTextWriter w, BrowserEntry entry, Compilation compilation)
        {
            foreach ((string controlType, string adapterType) in entry.ControlAdapters)
            {
                // Runtime adapter resolution (`HttpCapabilitiesBase.GetAdapter`)
                // keys by `controlType.AssemblyQualifiedName`, so a short-name
                // key never matches and the adapter silently doesn't wire.
                // Resolve through the Compilation to the type's full AQN —
                // matches what aspnet_compiler emits and what the runtime
                // looks up.
                string key = ResolveAdapterKey(controlType, compilation);
                w.Line($"browserCaps.Adapters[{CodeLiteral.Escape(key)}] = {CodeLiteral.Escape(adapterType)};");
            }
        }

        private static string ResolveAdapterKey(string controlType, Compilation compilation)
        {
            INamedTypeSymbol? symbol = compilation.GetTypeByMetadataName(controlType);
            if (symbol is null)
            {
                return controlType;
            }
            AssemblyIdentity identity = symbol.ContainingAssembly.Identity;
            string token = identity.PublicKeyToken.IsDefaultOrEmpty
                ? "null"
                : string.Concat(identity.PublicKeyToken.Select(b => b.ToString("x2")));
            string culture = string.IsNullOrEmpty(identity.CultureName) ? "neutral" : identity.CultureName;
            return $"{controlType}, {identity.Name}, Version={identity.Version}, Culture={culture}, PublicKeyToken={token}";
        }

        private static void EmitPopulateMatchedHeaders(IndentedTextWriter w, bool referencesUserAgent)
        {
            using (w.Block("protected override void PopulateMatchedHeaders(global::System.Collections.IDictionary dictionary)"))
            {
                w.Line("base.PopulateMatchedHeaders(dictionary);");
                if (referencesUserAgent)
                {
                    // Empty header key = User-Agent. The runtime keys the
                    // header-extraction dictionary by name; "" is reserved
                    // for the request's User-Agent.
                    w.Line("dictionary[\"\"] = null;");
                }
            }
        }

        private static void EmitPopulateBrowserElements(
            IndentedTextWriter w,
            ImmutableArray<BrowserEntry> entries,
            Dictionary<string, int> depth)
        {
            using (w.Block("protected override void PopulateBrowserElements(global::System.Collections.IDictionary dictionary)"))
            {
                w.Line("base.PopulateBrowserElements(dictionary);");
                // Only new entries (with id, not refining) register here —
                // refining entries augment an already-registered parent.
                foreach (BrowserEntry entry in entries)
                {
                    if (entry.Id is null || entry.RefId != null || entry.ParentId is null)
                    {
                        continue;
                    }
                    int d = depth.TryGetValue(entry.Id, out int depthValue) ? depthValue : 2;
                    string parentMethod = PascalCase(entry.ParentId);
                    w.Line($"dictionary[{CodeLiteral.Escape(entry.Id)}] = new global::System.Web.UI.Triplet({CodeLiteral.Escape(parentMethod)}, string.Empty, {d});");
                }
            }
        }

        // First letter upper, the rest lower — matches what aspnet_compiler
        // does with browser IDs when emitting method names ("IE11" → "Ie11",
        // "Mozilla" → "Mozilla", "Default" → "Default").
        private static string PascalCase(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return id;
            }
            if (id.Length == 1)
            {
                return char.ToUpperInvariant(id[0]).ToString();
            }
            return char.ToUpperInvariant(id[0]) + id.Substring(1).ToLowerInvariant();
        }
    }
}
