using System.CodeDom.Compiler;
using System.Collections.Generic;
using triaxis.WebForms.SourceGenerator.Model;

namespace triaxis.WebForms.SourceGenerator.Emit
{
    /// <summary>
    /// Emits the structural "frame" of a generated type. Pages, user controls
    /// and master pages share the ctor + <c>FrameworkInitialize</c> + tree shell,
    /// but only a Page is an <see cref="System.Web.IHttpHandler"/> with
    /// <c>ProcessRequest</c>/<c>GetTypeHashCode</c> and Page-only file-dependency
    /// bookkeeping; UserControl/MasterPage frames omit those (the members don't
    /// exist on their base types).
    /// </summary>
    internal static class PageFrameEmitter
    {
        public static string Emit(
            MarkupDirective directive,
            string virtualPath,
            string? treeBody = null,
            string? extraMethods = null,
            IEnumerable<string>? usings = null,
            IEnumerable<string>? contentPlaceHolderIds = null,
            bool requestValidationEnabled = true,
            ConstructorForwarding? forwarding = null)
        {
            bool isPage = directive.Kind == MarkupKind.Page;
            string typeName = GeneratedNaming.TypeNameFromVirtualPath(virtualPath);
            string appRelative = GeneratedNaming.AppRelativeVirtualPath(virtualPath);

            IndentedTextWriter w = CodeWriter.Create();
            w.Line("// <auto-generated/>");
            w.Line("#nullable disable");
            using (w.Block($"namespace {GeneratedNaming.Namespace}"))
            {
                if (usings != null)
                {
                    foreach (string ns in usings)
                    {
                        w.Line($"using {ns};");
                    }

                    w.Blank();
                }

                using (w.Block(ClassDeclaration(directive, typeName, isPage)))
                {
                    w.Line("private static bool __initialized;");
                    if (isPage)
                    {
                        w.Line("private static object __fileDependencies;");
                    }

                    w.Blank();

                    // Member order matches the ASP.NET compiler: Profile,
                    // SupportAutoEvents, ApplicationInstance, ctor, the control build
                    // methods, then the tree + lifecycle methods.
                    w.Line("protected global::System.Web.Profile.DefaultProfile Profile => (global::System.Web.Profile.DefaultProfile)this.Context.Profile;");
                    w.Blank();
                    if (!directive.AutoEventWireup)
                    {
                        w.Line("protected override bool SupportAutoEvents => false;");
                        w.Blank();
                    }

                    w.Line("protected global::ASP._global_asax ApplicationInstance => (global::ASP._global_asax)(object)this.Context.ApplicationInstance;");
                    w.Blank();

                    EmitConstructor(w, typeName, appRelative, isPage, directive.Kind == MarkupKind.Master ? contentPlaceHolderIds : null, forwarding);

                    if (!string.IsNullOrEmpty(extraMethods))
                    {
                        w.Blank();
                        w.Raw(extraMethods! + "\n");
                    }

                    w.Blank();
                    EmitBuildControlTree(w, typeName, directive, treeBody);
                    w.Blank();
                    EmitFrameworkInitialize(w, isPage, requestValidationEnabled);

                    if (isPage)
                    {
                        w.Blank();
                        EmitGetTypeHashCode(w, virtualPath);
                        w.Blank();
                        EmitProcessRequest(w);
                    }
                }
            }

            return w.ToSource();
        }

        private static string ClassDeclaration(MarkupDirective directive, string typeName, bool isPage)
        {
            string declaration = $"public class {typeName} : {ResolveBaseType(directive)}";
            if (isPage && directive.RequiresSessionState)
            {
                declaration += ", global::System.Web.SessionState.IRequiresSessionState";
            }

            if (isPage)
            {
                declaration += ", global::System.Web.IHttpHandler";
            }

            return declaration;
        }

        private static string ResolveBaseType(MarkupDirective directive)
        {
            if (!string.IsNullOrWhiteSpace(directive.Inherits))
            {
                return "global::" + directive.Inherits;
            }

            return directive.Kind switch
            {
                MarkupKind.Control => "global::System.Web.UI.UserControl",
                MarkupKind.Master => "global::System.Web.UI.MasterPage",
                _ => "global::System.Web.UI.Page",
            };
        }

        // The ASP.NET compiler marks the generated ctor, build methods and
        // lifecycle methods (but not the render delegates) with this attribute;
        // the writer supplies the indentation.
        public const string DebuggerNonUserCode = "[global::System.Diagnostics.DebuggerNonUserCode]";

        private static void EmitConstructor(IndentedTextWriter w, string typeName, string appRelative, bool isPage, IEnumerable<string>? contentPlaceHolderIds, ConstructorForwarding? forwarding)
        {
            // No injectable base constructor: the parameterless ctor carries the
            // initialization inline, matching the pre-4.7.2 compiler shape.
            if (forwarding == null)
            {
                w.Line(DebuggerNonUserCode);
                using (w.Block($"public {typeName}()"))
                {
                    EmitInitBody(w, appRelative, isPage, contentPlaceHolderIds);
                }

                return;
            }

            // The codebehind exposes parameterized constructor(s): forward each to
            // base(...) so dependency-injected arguments flow through, and run the
            // page's own initialization from a shared __Init(). The parameterless
            // ctor is emitted only when the base still offers one — otherwise the
            // generated class must not be default-constructible either.
            if (forwarding.BaseHasParameterlessConstructor)
            {
                w.Line(DebuggerNonUserCode);
                using (w.Block($"public {typeName}()"))
                {
                    w.Line("__Init();");
                }

                w.Blank();
            }

            foreach (ForwardedConstructor ctor in forwarding.Constructors)
            {
                w.Line(DebuggerNonUserCode);
                using (w.Block($"public {typeName}({ctor.ParameterList}) : base({ctor.BaseArguments})"))
                {
                    w.Line("__Init();");
                }

                w.Blank();
            }

            w.Line(DebuggerNonUserCode);
            using (w.Block("private void __Init()"))
            {
                EmitInitBody(w, appRelative, isPage, contentPlaceHolderIds);
            }
        }

        private static void EmitInitBody(IndentedTextWriter w, string appRelative, bool isPage, IEnumerable<string>? contentPlaceHolderIds)
        {
            w.Line($"AppRelativeVirtualPath = {Literal(appRelative)};");
            using (w.Block("if (!__initialized)"))
            {
                if (isPage)
                {
                    // GetWrappedFileDependencies is Page-only — never emit it on
                    // a UserControl/MasterPage frame.
                    w.Line($"__fileDependencies = GetWrappedFileDependencies(new string[] {{ {Literal(appRelative)} }});");
                }

                w.Line("__initialized = true;");
            }

            // A master page registers each ContentPlaceHolder id so content pages
            // can target them (ContentPlaceHolders is protected internal on MasterPage).
            if (contentPlaceHolderIds != null)
            {
                foreach (string id in contentPlaceHolderIds)
                {
                    w.Line($"this.ContentPlaceHolders.Add({Literal(id)});");
                }
            }
        }

        private static void EmitBuildControlTree(IndentedTextWriter w, string typeName, MarkupDirective directive, string? treeBody)
        {
            w.Line(DebuggerNonUserCode);
            using (w.Block($"private void __BuildControlTree({typeName} __ctrl)"))
            {
                if (treeBody != null)
                {
                    w.Raw(treeBody + "\n");
                }
                else
                {
                    if (directive.Kind == MarkupKind.Page && !string.IsNullOrEmpty(directive.Title))
                    {
                        w.Line($"__ctrl.Title = {Literal(directive.Title!)};");
                    }

                    w.Line("__ctrl.InitializeCulture();");
                    w.Line("// TODO(tree): __BuildControl* construction emitted by the tree slice.");
                }
            }
        }

        private static void EmitFrameworkInitialize(IndentedTextWriter w, bool isPage, bool requestValidationEnabled)
        {
            w.Line(DebuggerNonUserCode);
            using (w.Block("protected override void FrameworkInitialize()"))
            {
                w.Line("base.FrameworkInitialize();");
                w.Line("__BuildControlTree(this);");
                if (isPage)
                {
                    w.Line("AddWrappedFileDependencies(__fileDependencies);");
                    string mode = requestValidationEnabled ? "Enabled" : "Disabled";
                    w.Line($"ValidateRequestMode = global::System.Web.UI.ValidateRequestMode.{mode};");
                }
            }
        }

        private static void EmitGetTypeHashCode(IndentedTextWriter w, string virtualPath)
        {
            w.Line(DebuggerNonUserCode);
            using (w.Block("public override int GetTypeHashCode()"))
            {
                w.Line($"return {StableHash(virtualPath)};");
            }
        }

        private static void EmitProcessRequest(IndentedTextWriter w)
        {
            w.Line(DebuggerNonUserCode);
            using (w.Block("public override void ProcessRequest(global::System.Web.HttpContext context)"))
            {
                w.Line("base.ProcessRequest(context);");
            }
        }

        private static string Literal(string value) => CodeLiteral.Escape(value);

        private static int StableHash(string value)
        {
            unchecked
            {
                uint hash = 2166136261;
                foreach (char c in value)
                {
                    hash = (hash ^ c) * 16777619;
                }

                return (int)hash;
            }
        }
    }
}
