using System.CodeDom.Compiler;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using triaxis.WebForms.SourceGenerator.Model;

namespace triaxis.WebForms.SourceGenerator.Emit
{
    /// <summary>
    /// Emits one <c>ASP.&lt;Name&gt; : PageTheme</c> shell per
    /// <c>App_Themes\&lt;Name&gt;\</c> directory. The shell registers the
    /// theme's CSS files via <c>LinkedStyleSheets</c>, points
    /// <c>AppRelativeTemplateSourceDirectory</c> at the theme folder, and
    /// compiles each <c>.skin</c> file in the directory into per-skin
    /// <c>ControlSkinDelegate</c> methods registered in
    /// <c>__controlSkins</c> via <see cref="SkinEmitter"/>.
    /// </summary>
    internal static class ThemeEmitter
    {
        public static string Emit(
            ThemeEntry theme,
            ControlTypeResolver resolver,
            AttributeBinder binder,
            ChildClassifier classify,
            Compilation compilation,
            System.Collections.Generic.IEnumerable<string> serverPrefixes,
            System.Func<string?, string, bool, (string?, bool)>? resolveChild)
        {
            // aspnet_compiler reserves __control1 for the theme root and
            // counts skins from 2; pre-incremented by SkinEmitter so the
            // first allocation lands at 2.
            var skin = new SkinEmitter(resolver, binder, classify, compilation, serverPrefixes, resolveChild, counterStart: 1);
            foreach ((string virtualPath, string content) in theme.SkinFiles)
            {
                skin.EmitFile(content, virtualPath);
            }

            // The folder name doubles as an identifier, so it gets mangled for
            // the declaration; every path the shell reports keeps the folder's
            // real name.
            string declaredName = GeneratedNaming.Escaped(GeneratedNaming.Identifier(theme.Name));

            IndentedTextWriter w = CodeWriter.Create(0);
            w.Line("// <auto-generated/>");
            w.Line("#nullable disable");
            using (w.Block("namespace ASP"))
            using (w.Block($"public class {declaredName} : global::System.Web.UI.PageTheme"))
            {
                // HybridDictionary's initial-capacity ctor matches aspnet_compiler:
                // the count is the registered skin count.
                w.Line($"private global::System.Collections.Specialized.HybridDictionary __controlSkins = new global::System.Collections.Specialized.HybridDictionary({skin.Registrations.Count});");
                w.Blank();
                w.Line($"private string[] __linkedStyleSheets = new string[{theme.LinkedStyleSheets.Length}]");
                w.Line("{");
                w.Indent++;
                for (int i = 0; i < theme.LinkedStyleSheets.Length; i++)
                {
                    string css = theme.LinkedStyleSheets[i];
                    string suffix = i < theme.LinkedStyleSheets.Length - 1 ? "," : string.Empty;
                    w.Line($"{CodeLiteral.Escape(css)}{suffix}");
                }
                w.Indent--;
                w.Line("};");
                w.Blank();
                w.Line("private static bool __initialized;");
                w.Blank();
                foreach (string keyDecl in skin.SkinKeyFields)
                {
                    w.Line(keyDecl);
                    w.Blank();
                }
                w.Line($"protected override string AppRelativeTemplateSourceDirectory => {CodeLiteral.Escape("/App_Themes/" + theme.Name + "/")};");
                w.Blank();
                w.Line("protected override global::System.Collections.IDictionary ControlSkins => __controlSkins;");
                w.Blank();
                w.Line("protected override string[] LinkedStyleSheets => __linkedStyleSheets;");
                w.Blank();
                w.Line("[global::System.Diagnostics.DebuggerNonUserCode]");
                using (w.Block($"public {declaredName}()"))
                {
                    foreach (string reg in skin.Registrations)
                    {
                        w.Line(reg);
                    }
                    using (w.Block("if (!__initialized)"))
                    {
                        w.Line("__initialized = true;");
                    }
                }
                w.Blank();
                // Skin methods last; emitted in the order they were appended
                // (sub-property methods before their parent skin's top-level).
                w.Raw(skin.Methods);
            }
            return w.ToSource();
        }
    }
}
