using System.CodeDom.Compiler;
using System.Collections.Immutable;
using triaxis.WebForms.SourceGenerator.Model;

namespace triaxis.WebForms.SourceGenerator.Emit
{
    /// <summary>
    /// Emits one <c>ASP.&lt;Name&gt; : PageTheme</c> shell per
    /// <c>App_Themes\&lt;Name&gt;\</c> directory. The shell registers the
    /// theme's CSS files via <c>LinkedStyleSheets</c> and points
    /// <c>AppRelativeTemplateSourceDirectory</c> at the theme folder so
    /// the runtime can resolve theme-relative URLs. <c>.skin</c> file
    /// compilation (the <c>ControlSkins</c> dictionary and the
    /// <c>__BuildControl&lt;N&gt;()</c> shape that goes with it) is a
    /// separate, larger generator that processes a markup grammar
    /// against arbitrary control types — not handled here. Themes
    /// without .skin files still work for CSS linking with just the
    /// shell, which is the common case for stylesheet-only themes.
    /// </summary>
    internal static class ThemeEmitter
    {
        public static string Emit(ThemeEntry theme)
        {
            IndentedTextWriter w = CodeWriter.Create(0);
            w.Line("// <auto-generated/>");
            w.Line("#nullable disable");
            using (w.Block("namespace ASP"))
            using (w.Block($"public class {theme.Name} : global::System.Web.UI.PageTheme"))
            {
                // HybridDictionary's initial-capacity ctor matches aspnet_compiler:
                // the count is the skin-key count, but for a CSS-only theme it's 0.
                w.Line("private global::System.Collections.Specialized.HybridDictionary __controlSkins = new global::System.Collections.Specialized.HybridDictionary(0);");
                w.Blank();
                w.Line($"private string[] __linkedStyleSheets = new string[{theme.LinkedStyleSheets.Length}]");
                w.Line("{");
                w.Indent++;
                for (int i = 0; i < theme.LinkedStyleSheets.Length; i++)
                {
                    string css = theme.LinkedStyleSheets[i];
                    string suffix = i < theme.LinkedStyleSheets.Length - 1 ? "," : string.Empty;
                    w.Line($"{CodeLiteral.Escape(css)}{suffix}");
                }
                w.Indent--;
                w.Line("};");
                w.Blank();
                w.Line("private static bool __initialized;");
                w.Blank();
                w.Line($"protected override string AppRelativeTemplateSourceDirectory => {CodeLiteral.Escape("/App_Themes/" + theme.Name + "/")};");
                w.Blank();
                w.Line("protected override global::System.Collections.IDictionary ControlSkins => __controlSkins;");
                w.Blank();
                w.Line("protected override string[] LinkedStyleSheets => __linkedStyleSheets;");
                w.Blank();
                w.Line("[global::System.Diagnostics.DebuggerNonUserCode]");
                using (w.Block($"public {theme.Name}()"))
                using (w.Block("if (!__initialized)"))
                {
                    w.Line("__initialized = true;");
                }
            }
            return w.ToSource();
        }
    }
}
